<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoverColorsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('cover_colors')->insert([
            [
                'id' => 2,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز اسود',
                'image' => 'products/67087478ce0f5.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 3,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز احمر',
                'image' => 'products/6708777753b29.jpg',
                'description' => 'qqqqqqqq',
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 4,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز اسود',
                'image' => 'products/670877a82f4a3.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 5,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز جملي',
                'image' => 'products/670877c49bfe1.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 6,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز عنابي',
                'image' => 'products/670877dce6f72.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 7,
                'name' => 'بني',
                'tatriz_color' => 'مطرز بيج',
                'image' => 'products/6708780399873.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 8,
                'name' => 'بني',
                'tatriz_color' => 'مطرز جملي',
                'image' => 'products/67087823759c4.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 9,
                'name' => 'بيج',
                'tatriz_color' => 'مطرز بيج',
                'image' => 'products/670878406181b.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 10,
                'name' => 'رصاصي',
                'tatriz_color' => 'مطرز اسود',
                'image' => 'products/6708785b96684.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 4,
            ],
            [
                'id' => 11,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز اسود',
                'image' => 'products/670aae2604d95.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 5,
            ],
            [
                'id' => 12,
                'name' => 'بني',
                'tatriz_color' => 'مطرز نبي',
                'image' => 'products/670aae3912e76.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 5,
            ],
            [
                'id' => 13,
                'name' => 'بيج',
                'tatriz_color' => 'مطرز نبي',
                'image' => 'products/670aae67b1f16.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 5,
            ],
            [
                'id' => 14,
                'name' => 'جملي',
                'tatriz_color' => 'مطرز جملي',
                'image' => 'products/670aae7738d97.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 5,
            ],
            [
                'id' => 15,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز اسود',
                'image' => 'products/670aaf445f880.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 6,
            ],
            [
                'id' => 16,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز جملي',
                'image' => 'products/670aaf615ee12.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 6,
            ],
            [
                'id' => 17,
                'name' => 'أسود',
                'tatriz_color' => 'مطرز احمر',
                'image' => 'products/670aaf751c565.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 6,
            ],
            [
                'id' => 18,
                'name' => 'بني',
                'tatriz_color' => 'مطرز نبي',
                'image' => 'products/670aaf909d7e3.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 7,
            ],
            [
                'id' => 19,
                'name' => 'بيج',
                'tatriz_color' => 'مطرز بيج',
                'image' => 'products/670aafb29214e.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 8,
            ] ,
            [
                'id' => 20,
                'name' => 'بني',
                'tatriz_color' => 'مطرز نبي',
                'image' => 'products/670aaf909d7e3.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 8,
            ],
            [
                'id' => 21,
                'name' => 'بيج',
                'tatriz_color' => 'مطرز بيج',
                'image' => 'products/670aafb29214e.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 9,
            ],
            [
                'id' => 22,
                'name' => 'بيج',
                'tatriz_color' => 'مطرز جملي',
                'image' => 'products/670aafb29214e.jpg',
                'description' => null,
                'status' => 1,
                'category_id' => 9,
            ],
        ]);
    }
}
